In [ ]:
# Nama: Andi Oxy Raihan Machikami Rahman
# NIM: 231061006
# Prodi: Sains Data (SD23)

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv("/content/drive/MyDrive/Datasets/unclean_data_trial.csv", encoding='latin1')
data.head(5)

,movie_title,num_critic_for_reviews,duration,DIRECTOR_facebook_likes,actor_3_facebook_likes,ACTOR_1_facebook_likes,gross,num_voted_users,Cast_Total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,ACTOR_2_facebook_likes,imdb_score,title_year.1
0,Avatar?ÿ,723,178.0,10,855,1000,760505847,886204.0,4834.0,NaN,3054,237000000,2009,936.0,7.9,2009.0
1,Pirates of the Caribbean: At World's End?ÿ,302,NaN,563,1000,40000,309404152,471220.0,48350.0,NaN,1238,300000000,2007,5000.0,7.1,NaN
2,Spectre?ÿ,602,148.0,20,161,11000,200074175,275868.0,11700.0,1.0,994,245000000,2015,393.0,6.8,2015.0
3,The Dark Knight Rises?ÿ,813,NaN,22000,23000,27000,448130642,1144337.0,106759.0,NaN,2701,250000000,2012,23000.0,8.5,NaN
4,John Carter?ÿ,462,132.0,"""475""",530,640,73058679,212204.0,1873.0,1.0,738,263700000,2012,632.0,6.6,NaN

In [ ]:
data.isnull().sum()

movie_title                  0
num_critic_for_reviews       0
duration                     3
DIRECTOR_facebook_likes      2
actor_3_facebook_likes       0
ACTOR_1_facebook_likes       0
gross                        0
num_voted_users              1
Cast_Total_facebook_likes    2
facenumber_in_poster         5
num_user_for_reviews         0
budget                       0
title_year                   0
ACTOR_2_facebook_likes       1
imdb_score                   0
title_year.1                 7
dtype: int64

In [ ]:
#Mengganti salah satu karakter
x = "Campus??"
x = x.replace("?","")
print (x)

Campus

In [ ]:
data ["movie_title"] = data["movie_title"].str.replace("?","")
data ["movie_title"] = data["movie_title"].str.replace("ÿ","")
data ["title_year.1"] = data["title_year"].copy()
data ["DIRECTOR_facebook_likes"] = data["DIRECTOR_facebook_likes"].str.replace("\"","")
data

,movie_title,num_critic_for_reviews,duration,DIRECTOR_facebook_likes,actor_3_facebook_likes,ACTOR_1_facebook_likes,gross,num_voted_users,Cast_Total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,ACTOR_2_facebook_likes,imdb_score,title_year.1
0,Avatar,723,178.0,10,855,1000,760505847,886204.0,4834.0,NaN,3054,237000000,2009,936.0,7.9,2009
1,Pirates of the Caribbean: At World's End,302,NaN,563,1000,40000,309404152,471220.0,48350.0,NaN,1238,300000000,2007,5000.0,7.1,2007
2,Spectre,602,148.0,20,161,11000,200074175,275868.0,11700.0,1.0,994,245000000,2015,393.0,6.8,2015
3,The Dark Knight Rises,813,NaN,22000,23000,27000,448130642,1144337.0,106759.0,NaN,2701,250000000,2012,23000.0,8.5,2012
4,John Carter,462,132.0,475,530,640,73058679,212204.0,1873.0,1.0,738,263700000,2012,632.0,6.6,2012
5,Spider-Man 3,392,156.0,23,4000,24000,336530303,383056.0,46055.0,NaN,1902,258000000,2007,11000.0,6.2,2007
6,Tangled,324,NaN,15,284,799,200807262,294810.0,NaN,1.0,387,260000000,2010,553.0,7.8,2010
7,Avengers: Age of Ultron,635,141.0,10,19000,26000,458991599,462669.0,92000.0,4.0,1117,250000000,2015,21000.0,7.5,2015
8,Avengers: Age of Ultron,635,141.0,10,19000,26000,458991599,462669.0,92000.0,4.0,1117,250000000,2015,21000.0,7.5,2015
9,Harry Potter and the Half-Blood Prince,375,153.0,282,10000,25000,301956980,321795.0,58753.0,3.0,973,250000000,2009,11000.0,7.5,2009
10,Batman v Superman: Dawn of Justice,673,183.0,NaN,2000,15000,330249062,NaN,24450.0,NaN,3018,250000000,2016,NaN,6.9,2016
11,Superman Returns,434,169.0,NaN,903,18000,200069408,240396.0,NaN,2.0,2367,209000000,2006,10000.0,6.1,2006
12,Quantum of Solace,403,106.0,395,393,451,168368427,330784.0,2023.0,1.0,1243,200000000,2008,412.0,6.7,2008
13,Pirates of the Caribbean: Dead Man's Chest,313,151.0,563,1000,40000,423032628,522040.0,48486.0,2.0,1832,225000000,2006,5000.0,7.3,2006

In [ ]:
data.isnull().sum()

In [ ]:
#Mengganti data hilang

#Mengganti "durasi" dengan rata-rata
duration_mean = data['duration'].mean()
data['duration'].fillna(duration_mean, inplace=True)

#Mengganti "facebook like" dengan rata-rata
data['DIRECTOR_facebook_likes'] = data['DIRECTOR_facebook_likes'].astype(int) #mengubah tipe data dari str ke int
fblike_mean = data['DIRECTOR_facebook_likes'].mean()
data['DIRECTOR_facebook_likes'].fillna(fblike_mean, inplace=True)

#Mengganti "Num Vote" dengan rata-rata
numvote_mean = data['num_voted_users'].mean()
data['num_voted_users'].fillna(numvote_mean, inplace=True)

#Mengganti "Cast_Total_facebook_likes" dengan rata-rata
casttotal_mean = data['Cast_Total_facebook_likes'].mean()
data['Cast_Total_facebook_likes'].fillna(casttotal_mean, inplace=True)

#Mengganti "facenumber_in_poster" dengan rata-rata
facenumber_mean = data['facenumber_in_poster'].mean()
data['facenumber_in_poster'].fillna(facenumber_mean, inplace=True)

#Mengganti "ACTOR_2_facebook_likes" dengan rata-rata
actor_mean = data['ACTOR_2_facebook_likes'].mean()
data['ACTOR_2_facebook_likes'].fillna(actor_mean, inplace=True)

data

,movie_title,num_critic_for_reviews,duration,DIRECTOR_facebook_likes,actor_3_facebook_likes,ACTOR_1_facebook_likes,gross,num_voted_users,Cast_Total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,ACTOR_2_facebook_likes,imdb_score,title_year.1
0,Avatar,723,178.000000,10,855,1000,760505847,8.862040e+05,4834.000000,2.111111,3054,237000000,2009,936.000000,7.9,2009
1,Pirates of the Caribbean: At World's End,302,150.727273,563,1000,40000,309404152,4.712200e+05,48350.000000,2.111111,1238,300000000,2007,5000.000000,7.1,2007
2,Spectre,602,148.000000,20,161,11000,200074175,2.758680e+05,11700.000000,1.000000,994,245000000,2015,393.000000,6.8,2015
3,The Dark Knight Rises,813,150.727273,22000,23000,27000,448130642,1.144337e+06,106759.000000,2.111111,2701,250000000,2012,23000.000000,8.5,2012
4,John Carter,462,132.000000,475,530,640,73058679,2.122040e+05,1873.000000,1.000000,738,263700000,2012,632.000000,6.6,2012
5,Spider-Man 3,392,156.000000,23,4000,24000,336530303,3.830560e+05,46055.000000,2.111111,1902,258000000,2007,11000.000000,6.2,2007
6,Tangled,324,150.727273,15,284,799,200807262,2.948100e+05,44773.583333,1.000000,387,260000000,2010,553.000000,7.8,2010
7,Avengers: Age of Ultron,635,141.000000,10,19000,26000,458991599,4.626690e+05,92000.000000,4.000000,1117,250000000,2015,21000.000000,7.5,2015
8,Avengers: Age of Ultron,635,141.000000,10,19000,26000,458991599,4.626690e+05,92000.000000,4.000000,1117,250000000,2015,21000.000000,7.5,2015
9,Harry Potter and the Half-Blood Prince,375,153.000000,282,10000,25000,301956980,3.217950e+05,58753.000000,3.000000,973,250000000,2009,11000.000000,7.5,2009
10,Batman v Superman: Dawn of Justice,673,183.000000,10,2000,15000,330249062,4.621578e+05,24450.000000,2.111111,3018,250000000,2016,8455.846154,6.9,2016
11,Superman Returns,434,169.000000,10,903,18000,200069408,2.403960e+05,44773.583333,2.000000,2367,209000000,2006,10000.000000,6.1,2006
12,Quantum of Solace,403,106.000000,395,393,451,168368427,3.307840e+05,2023.000000,1.000000,1243,200000000,2008,412.000000,6.7,2008
13,Pirates of the Caribbean: Dead Man's Chest,313,151.000000,563,1000,40000,423032628,5.220400e+05,48486.000000,2.000000,1832,225000000,2006,5000.000000,7.3,2006